---
title: "figure-1-circle"
author: "Arthur Ryman"
date: '2017-03-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Unit Circle $S^1$

```{r,engine='tikz',fig.ext='pdf',fig.align='center', echo=FALSE}
\begin{tikzpicture}[scale=3]

% coordinates of point A
% thetaA = 30 degrees, xA = 0.866, yA = 0.500
\newcommand{\thetaA}{30}
\pgfmathsetmacro{\xA}{cos(\thetaA)}
\pgfmathsetmacro{\yA}{sin(\thetaA)}

% coordinates of point B
% thetaB = 35 degrees, xB = 0.819, yB = 0.574
\newcommand{\thetaB}{35}
\pgfmathsetmacro{\xB}{cos(\thetaB)}
\pgfmathsetmacro{\yB}{sin(\thetaB)}

\draw[step=1cm,help lines] (-1.4,-1.4) grid (1.4,1.4);

% draw the x-y axes
\draw[->] (-1.5,0) -- (1.5,0) node[anchor=west] {$x$};
\draw[->] (0,-1.5) -- (0,1.5) node[anchor=south] {$y$};
\draw (1,0) node[anchor=north west] {$1$};
\draw (-1,0) node[anchor=north east] {$-1$};
\draw (0,1) node[anchor=south east] {$1$};
\draw (0,-1) node[anchor=north east] {$-1$};

% draw the unit circle
\draw (0,0) circle (1);

% draw point A
\fill (\xA,\yA) circle (0.3mm) node[anchor=west] {$(\cos\theta,\sin\theta)$};

% draw the arc to A
\draw (0,0) -- (\xA, \yA);
\draw[->] (0.4,0) arc (0:\thetaA:0.4);
\draw (20:0.2) node[anchor=west] {$\theta$};

\end{tikzpicture}
```